services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'orion-mysql-container'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'orion'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '13306:3306'
